[package]
name = "relens-engine"
description = "Template rendering engine for relens"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
relens-domain = { version = "0.1.0", path = "../relens-domain" }
